- hosts: users
  become: no
  vars: 
    - username: ubuntu
    - group: ubuntu
  tasks:
    - name: add authorized_keys
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '/home/ubuntu/.ssh/authorized_keys') }}"
