- hosts: groups
  become: yes
  vars: 
    - username: ubuntu
    - group: ubuntu
  tasks:
    - name: install required packages
      apt:
        name:
          - make
          - qemu-utils
          - git
          - rsync
                     
    - name: modprobe nbd
      modprobe:
        name: nbd
        state: present

    - name: clone aitac-gns3-ospf
      git:
        repo: "https://github.com/shored/aitac-gns3-ospf.git"
        dest: "/home/ubuntu/aitac-gns3-ospf"
        force: yes

    - name: copy configs.txt
      copy: src=configs.txt dest=/home/ubuntu/aitac-gns3-ospf/scripts owner=ubuntu group=ubuntu

    - name: upload project files
      synchronize: src=~/work_dir dest=/home/ubuntu/aitac-gns3-ospf compress=no

    - name: Download frr image
      get_url:
        url: http://192.168.30.32/frr7.1-vm0.4.qcow2
        dest: /home/gns3/GNS3/images/

    - name: Download frr md5sum
      get_url:
        url: http://192.168.30.32/frr7.1-vm0.4.qcow2.md5sum
        dest: /home/gns3/GNS3/images/

    - name: Download QEMU/frr image
      get_url:
        url: http://192.168.30.32/QEMU/frr7.1-vm0.4.qcow2
        dest: /home/gns3/GNS3/images/QEMU/

    - name: Download QEMU/frr md5sum
      get_url:
        url: http://192.168.30.32/QEMU/frr7.1-vm0.4.qcow2.md5sum
        dest: /home/gns3/GNS3/images/QEMU/
        
    - name: exec scripts/extract.sh
      command: ./extract.sh
      args:
        chdir: /home/ubuntu/aitac-gns3-ospf/scripts

    - name: chown project files
      file:
        path: /home/gns3/GNS3
        owner: gns3
        group: gns3
        recurse: yes

    - name: restart gns3 service
      service:
        name: gns3
        state: restarted
        
